apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-ms
  template:
    metadata:
      labels:
        app: basic-ms
    spec:
      containers:
      - name: basic-microservice
        image: basic-microservice:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8085